# SQL Coding Questions

Important SQL interview queries, ready to run in Google Colab using SQLite (no setup needed).

**How to use:** run the setup cell first, then run any query cell. Or use **Runtime → Run all**.

## Setup: create the table and sample data

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")

conn.executescript("""
CREATE TABLE Employees (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    department VARCHAR(100),
    salary DECIMAL(10, 2)
);

INSERT INTO Employees (id, name, department, salary) VALUES
(1, 'Asha', 'CSE', 50000),
(2, 'Ravi', 'ECE', 45000),
(3, 'Priya', 'CSE', 60000),
(4, 'Arun', 'EEE', 40000),
(5, 'Meena', 'CSE', 60000);
""")

def run(query):
    """Run a SQL query and show the result as a table."""
    return pd.read_sql_query(query, conn)

run("SELECT * FROM Employees")

   id   name department  salary
0   1   Asha        CSE   50000
1   2   Ravi        ECE   45000
2   3  Priya        CSE   60000
3   4   Arun        EEE   40000
4   5  Meena        CSE   60000

## 1. Display employees from CSE

In [2]:
run("""
SELECT * FROM Employees
WHERE department = 'CSE';
""")

   id   name department  salary
0   1   Asha        CSE   50000
1   3  Priya        CSE   60000
2   5  Meena        CSE   60000

## 2. Sort employees by salary (highest first)

In [3]:
run("""
SELECT * FROM Employees
ORDER BY salary DESC;
""")

   id   name department  salary
0   3  Priya        CSE   60000
1   5  Meena        CSE   60000
2   1   Asha        CSE   50000
3   2   Ravi        ECE   45000
4   4   Arun        EEE   40000

## 3. Find average salary

In [4]:
run("""
SELECT AVG(salary) AS average_salary
FROM Employees;
""")

   average_salary
0         51000.0

## 4. Count employees by department

In [5]:
run("""
SELECT department, COUNT(*) AS employee_count
FROM Employees
GROUP BY department;
""")

  department  employee_count
0        CSE               3
1        ECE               1
2        EEE               1

## 5. Find highest salary

In [6]:
run("""
SELECT MAX(salary) AS highest_salary
FROM Employees;
""")

   highest_salary
0           60000

## 6. Find second highest distinct salary

In [7]:
run("""
SELECT MAX(salary) AS second_highest_salary
FROM Employees
WHERE salary < (SELECT MAX(salary) FROM Employees);
""")

   second_highest_salary
0                  50000

## 7. Find duplicate salaries

In [8]:
run("""
SELECT salary, COUNT(*) AS count
FROM Employees
GROUP BY salary
HAVING COUNT(*) > 1;
""")

   salary  count
0   60000      2

## 8. Highest salary in each department

In [9]:
run("""
SELECT department, MAX(salary) AS highest_salary
FROM Employees
GROUP BY department;
""")

  department  highest_salary
0        CSE           60000
1        ECE           45000
2        EEE           40000

## 9. Top N salaries (here N = 3)

In [10]:
run("""
SELECT DISTINCT salary
FROM Employees
ORDER BY salary DESC
LIMIT 3;
""")

   salary
0   60000
1   50000
2   45000

## 10. Employees whose name starts with a letter (here 'A')

In [11]:
run("""
SELECT * FROM Employees
WHERE name LIKE 'A%';
""")

   id  name department  salary
0   1  Asha        CSE   50000
1   4  Arun        EEE   40000